dist: trusty
python:
  - "3.5"
language: python
addons:
  apt:
    packages:
      - texlive-base
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-xetex
      - latexmk
      - lmodern
      - pgf
